/**
 * Induction — public client induction form.
 *
 * Accessed via /induction/:token — no auth required.
 * Token was generated by the mentor when sending the pack.
 *
 * Covers:
 *   - Service agreement consent (Section 2 of the pack)
 *   - Privacy notice consent (Section 4)
 *   - Client Intake / Session Zero form (Section 6)
 *
 * On submit, updates the induction_forms row in Supabase and sets completed_at.
 */
import { useEffect, useState } from 'react'
import { useParams, Link } from 'react-router-dom'
import { supabase } from '../lib/supabase'

const STEPS = ['About you', 'Where you are now', 'Looking ahead', 'Review & consent']

function StepIndicator({ current }) {
  return (
    <div style={{ display: 'flex', gap: 0, marginBottom: 32 }}>
      {STEPS.map((label, i) => {
        const done = i < current
        const active = i === current
        return (
          <div key={i} style={{ flex: 1, display: 'flex', flexDirection: 'column', alignItems: 'center', gap: 6 }}>
            <div style={{
              width: '100%', height: 3,
              background: done || active ? 'var(--gold)' : 'var(--line)',
              transition: 'background 0.2s',
            }} />
            <span style={{
              fontSize: 11, letterSpacing: '0.08em', textTransform: 'uppercase',
              color: active ? 'var(--navy)' : done ? 'var(--gold)' : 'var(--mute)',
              fontFamily: 'var(--font-body)', fontWeight: active ? 600 : 400,
              textAlign: 'center',
            }}>
              {label}
            </span>
          </div>
        )
      })}
    </div>
  )
}

function Field({ label, hint, required, children }) {
  return (
    <div className="form-row" style={{ marginBottom: 20 }}>
      <label style={{ fontWeight: 500 }}>
        {label}{required && <span style={{ color: 'var(--gold)', marginLeft: 4 }}>*</span>}
      </label>
      {hint && <div className="hint">{hint}</div>}
      {children}
    </div>
  )
}

export default function Induction() {
  const { token } = useParams()

  const [record, setRecord] = useState(null)
  const [status, setStatus] = useState('loading') // loading | not_found | already_done | form | done
  const [step, setStep] = useState(0)
  const [submitting, setSubmitting] = useState(false)
  const [error, setError] = useState('')

  const [form, setForm] = useState({
    full_name: '',
    preferred_name: '',
    date_of_birth: '',
    phone: '',
    referral_source: '',
    what_brings_you: '',
    whats_working: '',
    whats_harder: '',
    background_context: '',
    hoped_change: '',
    readiness_score: 0,
    service_consent: false,
    privacy_consent: false,
  })

  function set(key, val) { setForm(f => ({ ...f, [key]: val })) }

  useEffect(() => {
    if (!token) { setStatus('not_found'); return }
    supabase
      .from('induction_forms')
      .select('*')
      .eq('token', token)
      .maybeSingle()
      .then(({ data, error: e }) => {
        if (e || !data) { setStatus('not_found'); return }
        setRecord(data)
        if (data.completed_at) {
          setStatus('already_done')
          return
        }
        // Pre-fill name if profile data was included
        if (data.full_name) setForm(f => ({ ...f, full_name: data.full_name }))
        setStatus('form')
      })
  }, [token])

  function canAdvance() {
    if (step === 0) return form.full_name.trim().length > 0
    if (step === 1) return form.what_brings_you.trim().length > 0
    if (step === 2) return form.readiness_score > 0
    if (step === 3) return form.service_consent && form.privacy_consent
    return true
  }

  async function handleSubmit() {
    if (!record) return
    setSubmitting(true)
    setError('')

    const { error: e } = await supabase
      .from('induction_forms')
      .update({
        full_name:          form.full_name,
        preferred_name:     form.preferred_name,
        date_of_birth:      form.date_of_birth,
        phone:              form.phone,
        referral_source:    form.referral_source,
        what_brings_you:    form.what_brings_you,
        whats_working:      form.whats_working,
        whats_harder:       form.whats_harder,
        background_context: form.background_context,
        hoped_change:       form.hoped_change,
        readiness_score:    form.readiness_score,
        service_consent:    form.service_consent,
        privacy_consent:    form.privacy_consent,
        completed_at:       new Date().toISOString(),
      })
      .eq('token', token)

    setSubmitting(false)
    if (e) { setError(`Submission failed: ${e.message}`); return }

    // Notify mentor — fire-and-forget, don't block the success screen
    fetch('/.netlify/functions/send-email', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        type: 'induction_completed',
        data: {
          clientName:     form.full_name,
          readinessScore: form.readiness_score,
          whatBringsYou:  form.what_brings_you,
        },
      }),
    }).catch(() => {}) // silent fail — induction already saved

    setStatus('done')
  }

  if (status === 'loading') {
    return (
      <div style={{ background: 'var(--cream)', minHeight: '100vh', display: 'flex', alignItems: 'center', justifyContent: 'center' }}>
        <div className="loading">Loading your induction pack…</div>
      </div>
    )
  }

  if (status === 'not_found') {
    return (
      <div style={{ background: 'var(--cream)', minHeight: '100vh', padding: '60px 24px', maxWidth: 560, margin: '0 auto' }}>
        <div className="eyebrow" style={{ marginBottom: 8 }}>OurPath Guidance</div>
        <h1 style={{ fontFamily: 'var(--font-display)', color: 'var(--navy)' }}>Link not found</h1>
        <p style={{ color: 'var(--ink-soft)' }}>
          This induction link is invalid or has expired. Please contact your mentor
          at <a href="mailto:hello@ourpathguidance.co.uk">hello@ourpathguidance.co.uk</a>.
        </p>
      </div>
    )
  }

  if (status === 'already_done') {
    return (
      <div style={{ background: 'var(--cream)', minHeight: '100vh', padding: '60px 24px', maxWidth: 560, margin: '0 auto' }}>
        <div className="eyebrow" style={{ marginBottom: 8 }}>OurPath Guidance</div>
        <h1 style={{ fontFamily: 'var(--font-display)', color: 'var(--navy)' }}>Already submitted</h1>
        <p style={{ color: 'var(--ink-soft)' }}>
          Your induction pack has already been completed. Your mentor has received your responses.
          If you need to change anything, get in touch at{' '}
          <a href="mailto:hello@ourpathguidance.co.uk">hello@ourpathguidance.co.uk</a>.
        </p>
      </div>
    )
  }

  if (status === 'done') {
    return (
      <div style={{ background: 'var(--cream)', minHeight: '100vh', padding: '60px 24px', maxWidth: 600, margin: '0 auto' }}>
        <div style={{ marginBottom: 32, paddingBottom: 20, borderBottom: '1px solid var(--gold)' }}>
          <div style={{ fontFamily: 'var(--font-display)', fontSize: 14, color: 'var(--gold)', letterSpacing: '0.1em', textTransform: 'uppercase', marginBottom: 8 }}>
            OurPath Guidance
          </div>
          <h1 style={{ fontFamily: 'var(--font-display)', fontSize: 36, color: 'var(--navy)', margin: 0 }}>
            Submitted. Thank you.
          </h1>
        </div>
        <p style={{ fontFamily: 'var(--font-display)', fontStyle: 'italic', fontSize: 17, color: 'var(--navy)', lineHeight: 1.65 }}>
          Your responses have been received. Your mentor will review them before your first session.
        </p>
        <p style={{ fontSize: 14, color: 'var(--ink-soft)', lineHeight: 1.7 }}>
          There is nothing more to do right now. If your session is not yet booked,
          your mentor will be in touch to arrange a time.
        </p>
        <p style={{ fontSize: 13, color: 'var(--mute)' }}>
          Questions? Email <a href="mailto:hello@ourpathguidance.co.uk">hello@ourpathguidance.co.uk</a>
        </p>
      </div>
    )
  }

  return (
    <div style={{ background: 'var(--cream)', minHeight: '100vh' }}>
      <div style={{ maxWidth: 680, margin: '0 auto', padding: '40px 24px 80px' }}>

        {/* Header */}
        <div style={{ marginBottom: 32 }}>
          <div style={{
            fontFamily: 'var(--font-display)', fontSize: 13,
            color: 'var(--gold)', letterSpacing: '0.1em', textTransform: 'uppercase',
            marginBottom: 8,
          }}>
            OurPath Guidance · Client Induction
          </div>
          <h1 style={{ fontFamily: 'var(--font-display)', fontSize: 32, color: 'var(--navy)', margin: 0, lineHeight: 1.1 }}>
            Welcome. A few things before your first session.
          </h1>
          <p style={{ color: 'var(--ink-soft)', marginTop: 12, lineHeight: 1.65, fontSize: 15 }}>
            Your mentor has prepared this short pack. It takes 5–10 minutes.
            Your answers stay between you and your mentor — no one else sees them.
          </p>
        </div>

        <StepIndicator current={step} />

        <div className="card" style={{ padding: '24px', overflowX: 'hidden' }}>

          {/* ── Step 0: About you ── */}
          {step === 0 && (
            <>
              <h2 style={{ fontFamily: 'var(--font-display)', fontSize: 22, color: 'var(--navy)', margin: '0 0 20px' }}>
                About you
              </h2>

              <Field label="Full name" required>
                <input
                  type="text" value={form.full_name}
                  onChange={e => set('full_name', e.target.value)}
                  placeholder="As you'd like it on your record"
                />
              </Field>

              <Field label="Preferred name" hint="What your mentor should call you in sessions">
                <input
                  type="text" value={form.preferred_name}
                  onChange={e => set('preferred_name', e.target.value)}
                  placeholder="First name, nickname — whatever feels right"
                />
              </Field>

              <Field label="Date of birth">
                <input
                  type="date" value={form.date_of_birth}
                  onChange={e => set('date_of_birth', e.target.value)}
                />
              </Field>

              <Field label="Phone number" hint="In case we need to reach you about a session">
                <input
                  type="tel" value={form.phone}
                  onChange={e => set('phone', e.target.value)}
                  placeholder="07700 000000"
                />
              </Field>

              <Field label="How did you hear about OurPath?">
                <input
                  type="text" value={form.referral_source}
                  onChange={e => set('referral_source', e.target.value)}
                  placeholder="Word of mouth, social media, referral…"
                />
              </Field>
            </>
          )}

          {/* ── Step 1: Where you are now ── */}
          {step === 1 && (
            <>
              <h2 style={{ fontFamily: 'var(--font-display)', fontSize: 22, color: 'var(--navy)', margin: '0 0 6px' }}>
                Where you are now
              </h2>
              <p style={{ fontSize: 13, color: 'var(--mute)', fontStyle: 'italic', marginBottom: 20 }}>
                No pressure to be polished. A few honest sentences is better than a polished paragraph.
              </p>

              <Field label="What brings you here?" required hint="Not the full story — the thing that made you reach out">
                <textarea
                  style={{ minHeight: 100 }}
                  value={form.what_brings_you}
                  onChange={e => set('what_brings_you', e.target.value)}
                  placeholder="In your own words…"
                />
              </Field>

              <Field label="What's working well right now?" hint="Even small things count">
                <textarea
                  style={{ minHeight: 80 }}
                  value={form.whats_working}
                  onChange={e => set('whats_working', e.target.value)}
                  placeholder="Work, family, faith, health — anything that feels stable or positive"
                />
              </Field>

              <Field label="What's feeling harder?" hint="What's drawing most of your attention or energy?">
                <textarea
                  style={{ minHeight: 80 }}
                  value={form.whats_harder}
                  onChange={e => set('whats_harder', e.target.value)}
                  placeholder="What feels stuck, heavy, or unclear?"
                />
              </Field>

              <Field label="Background that might help us" hint="Family, community, faith, study, work — anything relevant to understanding your situation">
                <textarea
                  style={{ minHeight: 80 }}
                  value={form.background_context}
                  onChange={e => set('background_context', e.target.value)}
                  placeholder="Only what feels relevant — nothing is required here"
                />
              </Field>
            </>
          )}

          {/* ── Step 2: Looking ahead ── */}
          {step === 2 && (
            <>
              <h2 style={{ fontFamily: 'var(--font-display)', fontSize: 22, color: 'var(--navy)', margin: '0 0 20px' }}>
                Looking ahead
              </h2>

              <Field label="What would you like to be different by the end of these sessions?" hint="Not the final destination — just a sense of what a shift would feel like">
                <textarea
                  style={{ minHeight: 90 }}
                  value={form.hoped_change}
                  onChange={e => set('hoped_change', e.target.value)}
                  placeholder="What would count as meaningful progress for you?"
                />
              </Field>

              <Field label="How ready do you feel to work on this right now?" required hint="1 = not at all ready · 5 = fully ready and committed">
                <div style={{ display: 'flex', gap: 10, marginTop: 4 }}>
                  {[1, 2, 3, 4, 5].map(v => (
                    <button
                      key={v}
                      type="button"
                      onClick={() => set('readiness_score', v)}
                      style={{
                        flex: 1, padding: '10px 4px',
                        border: `1px solid ${form.readiness_score === v ? 'var(--navy)' : 'var(--line)'}`,
                        borderRadius: 4,
                        background: form.readiness_score === v ? 'var(--navy)' : 'var(--cream)',
                        color: form.readiness_score === v ? 'var(--cream)' : 'var(--charcoal)',
                        fontFamily: 'var(--font-body)', fontSize: 16,
                        cursor: 'pointer', transition: 'all 0.12s',
                      }}
                    >
                      {v}
                    </button>
                  ))}
                </div>
                {form.readiness_score > 0 && (
                  <div style={{ fontSize: 12, color: 'var(--gold)', marginTop: 6 }}>
                    {['', 'Not yet ready', 'Starting to consider it', 'Reasonably ready', 'Ready', 'Fully ready and committed'][form.readiness_score]}
                  </div>
                )}
              </Field>
            </>
          )}

          {/* ── Step 3: Review & consent ── */}
          {step === 3 && (
            <>
              <h2 style={{ fontFamily: 'var(--font-display)', fontSize: 22, color: 'var(--navy)', margin: '0 0 16px' }}>
                Review & consent
              </h2>

              <div style={{
                background: 'var(--cream)',
                border: '1px solid var(--line)',
                borderRadius: 4,
                padding: '16px 18px',
                marginBottom: 20,
                fontSize: 13, color: 'var(--charcoal)', lineHeight: 1.7,
                overflowWrap: 'break-word', wordBreak: 'break-word',
              }}>
                <div style={{ fontWeight: 600, color: 'var(--navy)', marginBottom: 6 }}>What this service is</div>
                OurPath Guidance offers non-clinical, preventative developmental mentoring.
                It is not counselling, therapy, diagnosis, or a crisis service.
                Participation is voluntary and you can stop at any time without penalty.
                <br /><br />
                <div style={{ fontWeight: 600, color: 'var(--navy)', marginBottom: 6 }}>Confidentiality</div>
                What you share is treated confidentially, except where there is a risk of harm — to
                yourself or others. In those cases, your mentor is required to escalate to the
                appropriate person to keep you safe.
                <br /><br />
                <div style={{ fontWeight: 600, color: 'var(--navy)', marginBottom: 6 }}>Your data</div>
                Minimal records are kept securely and handled in line with UK GDPR.
                Records are seen only by your mentor unless safeguarding requires otherwise.
                You have the right to access, correct, or request deletion of your data at any time.
                Contact: <a href="mailto:hello@ourpathguidance.co.uk">hello@ourpathguidance.co.uk</a>
              </div>

              <div style={{ display: 'flex', flexDirection: 'column', gap: 14, marginBottom: 20 }}>
                <label style={{ display: 'flex', gap: 12, alignItems: 'flex-start', cursor: 'pointer' }}>
                  <input
                    type="checkbox" checked={form.service_consent}
                    onChange={e => set('service_consent', e.target.checked)}
                    style={{ marginTop: 3, flexShrink: 0 }}
                  />
                  <span style={{ fontSize: 14, color: 'var(--charcoal)', lineHeight: 1.6 }}>
                    I understand that OurPath is a non-clinical developmental mentoring service —
                    not therapy, diagnosis, or a crisis service. I am participating voluntarily and
                    understand I can withdraw at any time.
                  </span>
                </label>
                <label style={{ display: 'flex', gap: 12, alignItems: 'flex-start', cursor: 'pointer' }}>
                  <input
                    type="checkbox" checked={form.privacy_consent}
                    onChange={e => set('privacy_consent', e.target.checked)}
                    style={{ marginTop: 3, flexShrink: 0 }}
                  />
                  <span style={{ fontSize: 14, color: 'var(--charcoal)', lineHeight: 1.6 }}>
                    I have read and understood how my information is handled. I consent to
                    OurPath Guidance holding minimal records for the purpose of delivering the service.
                  </span>
                </label>
              </div>

              {error && <div className="auth-error" style={{ marginBottom: 16 }}>{error}</div>}
            </>
          )}

        </div>

        {/* Navigation */}
        <div style={{ display: 'flex', justifyContent: 'space-between', marginTop: 20 }}>
          {step > 0 ? (
            <button
              type="button"
              className="btn btn-ghost"
              onClick={() => setStep(s => s - 1)}
            >
              ← Back
            </button>
          ) : <div />}

          {step < STEPS.length - 1 ? (
            <button
              type="button"
              className="btn btn-primary"
              disabled={!canAdvance()}
              onClick={() => setStep(s => s + 1)}
            >
              Continue →
            </button>
          ) : (
            <button
              type="button"
              className="btn btn-primary"
              disabled={!canAdvance() || submitting}
              onClick={handleSubmit}
            >
              {submitting ? 'Submitting…' : 'Submit induction pack'}
            </button>
          )}
        </div>

        <p style={{ fontSize: 12, color: 'var(--mute)', textAlign: 'center', marginTop: 24 }}>
          OurPath Guidance Ltd · Registered in England & Wales ·{' '}
          <Link to="/privacy" style={{ color: 'var(--mute)' }}>Privacy Policy</Link>
        </p>
      </div>
    </div>
  )
}
